name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build application
        run: mvn clean compile


  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkstyle
        run: mvn checkstyle:check


  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: mvn test


  sonar:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Analysis
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=cephora52_TaskManager \
          -Dsonar.organization=cephora52 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}


  security_scan:
    runs-on: ubuntu-latest
    needs: sonar

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency security scan
        run: mvn org.owasp:dependency-check-maven:check


  docker:
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build jar
        run: mvn clean package -DskipTests

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager


  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Run container
        run: |
          docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager